#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Row:
    plugin_id: str
    plugin_type: str
    uses_sql: bool
    uses_sql_exec: bool


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _plugin_type(manifest_path: Path) -> str:
    for line in _read_text(manifest_path).splitlines():
        if line.strip().startswith("type:"):
            return line.split(":", 1)[1].strip()
    return ""


def generate(plugins_root: Path) -> list[Row]:
    out: list[Row] = []
    for pdir in sorted([p for p in plugins_root.iterdir() if p.is_dir()], key=lambda p: p.name):
        manifest = pdir / "plugin.yaml"
        entry = pdir / "plugin.py"
        if not manifest.exists() or not entry.exists():
            continue
        ptype = _plugin_type(manifest)
        text = _read_text(entry)
        out.append(
            Row(
                plugin_id=pdir.name,
                plugin_type=ptype,
                uses_sql=("ctx.sql" in text),
                uses_sql_exec=("ctx.sql_exec" in text),
            )
        )
    return out


def _as_json(items: list[Row]) -> dict[str, Any]:
    return {
        "plugin_count": len(items),
        "uses_sql": sum(1 for i in items if i.uses_sql),
        "uses_sql_exec": sum(1 for i in items if i.uses_sql_exec),
        "plugins": [
            {
                "plugin_id": i.plugin_id,
                "plugin_type": i.plugin_type,
                "uses_sql": bool(i.uses_sql),
                "uses_sql_exec": bool(i.uses_sql_exec),
            }
            for i in items
        ],
    }


def _as_md(items: list[Row]) -> str:
    lines: list[str] = []
    lines.append("# SQL Assist Adoption Matrix")
    lines.append("")
    lines.append("Generated by `scripts/sql_assist_adoption_matrix.py`.")
    lines.append("")
    lines.append("| Plugin | Type | ctx.sql | ctx.sql_exec |")
    lines.append("|---|---|---:|---:|")
    for i in items:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{i.plugin_id}`",
                    i.plugin_type or "",
                    str(int(i.uses_sql)),
                    str(int(i.uses_sql_exec)),
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--plugins-root", default="plugins")
    ap.add_argument("--out-json", default="docs/sql_assist_adoption_matrix.json")
    ap.add_argument("--out-md", default="docs/sql_assist_adoption_matrix.md")
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()

    items = generate((ROOT / args.plugins_root).resolve())
    payload = _as_json(items)
    out_json = (ROOT / args.out_json).resolve()
    out_md = (ROOT / args.out_md).resolve()
    json_text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    md_text = _as_md(items)

    if args.verify:
        if not out_json.exists() or out_json.read_text(encoding="utf-8") != json_text:
            return 2
        if not out_md.exists() or out_md.read_text(encoding="utf-8") != md_text:
            return 2
        return 0

    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json_text, encoding="utf-8")
    out_md.write_text(md_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

